### ISSUE TITLE
useModal hooks用不了

### ISSUE THREAD

**Issue by zivenday** [wowlusitong/react-use-modal#23]
会提示 showModal不存在
![image](https://user-images.githubusercontent.com/6906169/117252031-05b52c00-ae78-11eb-9d3b-80388ab3da90.png)

**Comment by wowlusitong** [comment]
可以考虑install后直接`import { useModal } from 'react-use-modal';`

**Comment by zivenday** [comment]
`<ModalProvder>没加导致`
