### ISSUE TITLE
antd form 3.26 版本 搭配用起来有问题，校验标红出不来

### ISSUE THREAD

**Issue by zivenday** [wowlusitong/react-use-modal#32]
实例：https://codesandbox.io/s/dreamy-tharp-5d8xy

**Comment by wowlusitong** [comment]
@zivenday  将modal独立出来一个组件就好了，帮你修改了下

https://codesandbox.io/s/intelligent-darwin-egedj?file=/src/App.js

**Comment by zivenday** [comment]
> @zivenday 将modal独立出来一个组件就好了，帮你修改了下
> 
> https://codesandbox.io/s/intelligent-darwin-egedj?file=/src/App.js

你知道具体是什么原因造成的吗？
